version: '2'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfiles/web.dockerfile
    volumes:
      - .:/DIVE-backend
    ports:
      - "8081:8081"
    links:
      - db

  worker:
    build:
      context: .
      dockerfile: ./Dockerfiles/worker.dockerfile
    tty: true
    volumes:
      - .:/DIVE-backend
    links:
      - rabbitmq
      - db

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_VHOST=dive

  db:
    image: sameersbn/postgresql
    hostname: db
    volumes_from:
      - dbdata
    environment:
      - DB_USER=admin
      - DB_PASS=password
      - DB_NAME=dive
      - PSQL_TRUST_LOCALNET
    ports:
      - "5432:5432"

  dbdata:
    image: sameersbn/postgresql
    volumes:
      - /var/lib/postgresql
