version: 1

disable_existing_loggers: True

formatters:
    detailed:
        format: '[%(asctime)s] [%(levelname)s] %(name)s:%(lineno)d:%(funcName)s:%(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'
    colored:
        (): 'colorlog.ColoredFormatter'
        format: '[%(asctime)s] %(log_color)s [%(levelname)s] %(reset)s %(name)s:%(lineno)d:%(funcName)s:%(blue)s%(message)s'
        datefmt: '%Y-%m-%d %H:%M:%S'

handlers:
    console:
        class: logging.StreamHandler
        level: DEBUG
        formatter: colored
        stream: ext://sys.stdout

    log_file:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: detailed
        filename: logs/dive.log
        encoding: utf8
        backupCount: 20

loggers:
  dive.core.cors:
    level: ERROR

root:
    level: DEBUG
    handlers: [console, log_file]
    propagate: true
