dive_url: "http://localhost:8081"
jobs:
  - params: {}
    actions:
    - action_module: "benchmark.action.upload"
      action_class_name: "Upload"
      file: "../benchmark-sample/nba_winrates.csv"
      delay: 3
    - action_module: "benchmark.action.explore"
      action_class_name: "Explore"
      delay: 0
